version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pnpm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
