services:
  # FastAPI Application
  gaia:
    container_name: gaia
    build: .
    working_dir: /app
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
      ]
    environment:
      DEBUG: 1
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "rpc://"
    volumes:
      - .:/app
    ports:
      - "8000:80"
    restart: on-failure

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Celery Worker
  celery_worker:
    container_name: celery_worker
    build: .
    working_dir: /app
    command:
      [
        "python",
        "-m",
        "celery",
        "-A",
        "app.worker",
        "worker",
        "--loglevel=info",
      ]
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "rpc://"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
