services:
  # FastAPI Application
  gaia:
    container_name: gaia
    build: .
    image: gaia-image
    working_dir: /app
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
      ]
    environment:
      DEBUG: 1
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "rpc://"
      PYTHONUNBUFFERED: 1
      FORCE_COLOR: 1
      CHROMADB_DEVELOPMENT_HOST: "chromadb"
      CHROMADB_DEVELOPMENT_PORT: "8000"
    volumes:
      - .:/app
    ports:
      - "8000:80"
    restart: on-failure
    tty: true
    stdin_open: true
    depends_on:
      - chromadb

  # RabbitMQ Service
  rabbitmq:
    profiles: ["celery"]
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Celery Worker
  celery_worker:
    profiles: ["celery"]
    container_name: celery_worker
    image: gaia-image
    working_dir: /app
    command:
      [
        "python",
        "-m",
        "celery",
        "-A",
        "app.worker",
        "worker",
        "--loglevel=info",
      ]
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "rpc://"
      CHROMADB_DEVELOPMENT_HOST: "chromadb"
      CHROMADB_DEVELOPMENT_PORT: "8000"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - chromadb

  # ChromaDB Service
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    ports:
      - "8080:8000"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  chroma_data:
