name: Quality Checks

on:
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  frontend-build:
    if: ${{ contains(github.event.pull_request.changed_files, 'frontend/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create Build
        env:
          NEXT_PUBLIC_API_BASE_URL: "http://fake-api-for-build.example.com"
          NEXT_PUBLIC_APP_URL: "https://fake-app-url.example.com"
          NEXT_PUBLIC_SOCKET_URL: "wss://fake-socket.example.com"
        run: pnpm build

  backend-checks:
    if: ${{ contains(github.event.pull_request.changed_files, 'backend/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "backend/requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install types-redis types-requests

      - name: Run pre-commit checks
        run: pre-commit run --all-files
